language: python
python:
  - "2.7"
env:
  - PYTHONPATH=$PYTHONPATH:$TRAVIS_BUILD_DIR
# command to install dependencies
install:
  - pip install coverage pytest
  - pip install alibabacloud-tea-py2
# command to run tests
script:
  - coverage run --source=alibabacloud_credentials -m pytest tests/
  - wget --no-check-certificate https://codecov.io/bash -O codecov.sh
  - bash codecov.sh -cF "python"